apiVersion: v1
kind: Service
metadata:
  name: k8s-gateway-api-demo-service-e7570aa
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: k8s-gateway-api-demo-e7570aa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-gateway-api-demo-e7570aa
  name: k8s-gateway-api-demo-e7570aa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-gateway-api-demo-e7570aa
  template:
    metadata:
      labels:
        app: k8s-gateway-api-demo-e7570aa
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: msathetech/k8s-gateway-demo:e7570aa
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 10
        name: k8s-gateway-api-demo
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: "0.5"
