apiVersion: v1
kind: Service
metadata:
  name: k8s-gateway-api-demo-service-399987d
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: k8s-gateway-api-demo-399987d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-gateway-api-demo-399987d
  name: k8s-gateway-api-demo-399987d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-gateway-api-demo-399987d
  template:
    metadata:
      labels:
        app: k8s-gateway-api-demo-399987d
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: msathetech/k8s-gateway-demo:399987d
        imagePullPolicy: Always
        name: k8s-gateway-api-demo
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: "0.5"
