kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  labels:
    gateway: external-http
  name: k8s-gateway-api-demo
spec:
  gateways:
    allow: All
  rules:
  - forwardTo:
    - port: 8080
      serviceName: k8s-gateway-api-demo-service-ff3b85e
      weight: 100
    - {}
    matches:
    - path:
        type: Prefix
        value: /
